export type SelectOption = { value: string; label: string };

export const JOB_OPTIONS: SelectOption[] = [
  { value: "assistant", label: "Assistant" },
  { value: "automation-analyst", label: "Automation Analyst" },
  { value: "automation-director", label: "Automation Director" },
  { value: "automation-manager", label: "Automation Manager" },
  { value: "business-consultant", label: "Business Consultant" },
  { value: "buyer", label: "Buyer" },
  { value: "commercial-director", label: "Commercial Director" },
  { value: "digital-manager", label: "Digital Manager" },
  { value: "operations-director", label: "Operations Director" },
  { value: "industrial-director", label: "Industrial Director" },
  { value: "industrial-manager", label: "Industrial Manager" },
  { value: "innovation-analyst", label: "Innovation Analyst" },
  { value: "innovation-manager", label: "Innovation Manager" },
  { value: "intern", label: "Intern" },
  { value: "it-consultant", label: "IT Consultant" },
  { value: "it-director", label: "IT Director" },
  { value: "it-manager", label: "IT Manager" },
  { value: "maintenance-consultant", label: "Maintenance Consultant" },
  { value: "maintenance-coordinator", label: "Maintenance Coordinator" },
  { value: "maintenance-engineer", label: "Maintenance Engineer" },
  { value: "maintenance-manager", label: "Maintenance Manager" },
  { value: "maintenance-planner", label: "Maintenance Planner" },
  { value: "maintenance-supervisor", label: "Maintenance Supervisor" },
  { value: "maintenance-technician", label: "Maintenance Technician" },
  { value: "operations-coordinator", label: "Operations Coordinator" },
  { value: "operations-manager", label: "Operations Manager" },
  { value: "partnership-director", label: "Partnership Director" },
  { value: "predictive-analyst", label: "Predictive Analyst" },
  { value: "predictive-technician", label: "Predictive Technician" },
  { value: "process-coordinator", label: "Process Coordinator" },
  { value: "process-manager", label: "Process Manager" },
  { value: "procurement-manager", label: "Procurement Manager" },
  { value: "production-operator", label: "Production Operator" },
  { value: "plant-manager", label: "Plant Manager" },
  { value: "reliability-engineer", label: "Reliability Engineer" },
  { value: "reliability-manager", label: "Reliability Manager" },
  { value: "sales-executive", label: "Sales Executive" },
  { value: "sales-representative", label: "Sales Representative" },
  { value: "supply-manager", label: "Supply Manager" },
];

export const INDUSTRY_OPTIONS: SelectOption[] = [
  { value: "aeronautics", label: "Aeronautics" },
  { value: "agriculture", label: "Agriculture" },
  { value: "animal-nutrition", label: "Animal Nutrition" },
  { value: "airports", label: "Airports" },
  { value: "automotive", label: "Automotive" },
  { value: "beverage", label: "Beverage" },
  { value: "bioenergy", label: "Bioenergy" },
  { value: "buildings", label: "Buildings" },
  { value: "building-complex", label: "Building Complex" },
  { value: "cement", label: "Cement" },
  { value: "ceramics", label: "Ceramics" },
  { value: "chemical", label: "Chemical" },
  { value: "construction", label: "Construction" },
  { value: "consumer-goods", label: "Consumer Goods" },
  { value: "cosmetics", label: "Cosmetics" },
  { value: "data-center", label: "Data Center" },
  { value: "distributors", label: "Distributors" },
  { value: "education", label: "Education" },
  { value: "electronics", label: "Electronics" },
  { value: "energy", label: "Energy" },
  { value: "facilities", label: "Facilities" },
  { value: "fertilizers", label: "Fertilizers" },
  { value: "food", label: "Food" },
  { value: "foundry", label: "Foundry" },
  { value: "furniture", label: "Furniture" },
  { value: "franchising", label: "Franchising" },
  { value: "glass", label: "Glass" },
  { value: "hospitals", label: "Hospitals" },
  { value: "hygiene", label: "Hygiene" },
  { value: "logistics", label: "Logistics" },
  { value: "machinery", label: "Machinery" },
  { value: "machining-cnc", label: "Machining CNC" },
  { value: "maritime", label: "Maritime" },
  { value: "metal-mechanics", label: "Metal-mechanics" },
  { value: "metallurgy", label: "Metallurgy" },
  { value: "mills", label: "Mills" },
  { value: "mining", label: "Mining" },
  { value: "oil-and-gas", label: "Oil And Gas" },
  { value: "other", label: "Other" },
  { value: "packaging", label: "Packaging" },
  { value: "pulp-and-paper", label: "Pulp and Paper" },
  { value: "pharmaceutical", label: "Pharmaceutical" },
  { value: "plastic", label: "Plastic" },
  { value: "power-plant", label: "Power Plant" },
  { value: "shopping-mall", label: "Shopping Mall" },
  { value: "sanitation", label: "Sanitation" },
  { value: "service-provider", label: "Service Provider" },
  { value: "stores", label: "Stores" },
  { value: "solar-energy", label: "Solar Energy" },
  { value: "sugar-and-alcohol", label: "Sugar And Alcohol" },
  { value: "supermarket", label: "Supermarket" },
  { value: "textile", label: "Textile" },
  { value: "waste", label: "Waste" },
  { value: "wholesaler", label: "Wholesaler" },
  { value: "wood", label: "Wood" },
];

export function getSolutionOptions(t: (key: string) => string): SelectOption[] {
  return [
    { value: "condition-monitoring", label: t("solutionOptionCM") },
    { value: "cmms", label: t("solutionOptionCMMS") },
    { value: "oee", label: t("solutionOptionOEE") },
  ];
}
